runtime: python310
entrypoint: gunicorn -b :$PORT main:app

instance_class: F4

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

runtime_config:
  python_version: 3.10.7
